= Projektantrag
Vrhovac David | 2024-10-19
ifndef::imagesdir[:imagesdir: images]

== Vokabel Lernapp

=== Projektbeschreibung
Die Idee des Projekts ist eine interaktive Vokabel Lernapp, die Benutzern hilft neue Wörter effizienter zu
lernen und ihren Wortschatz zu erweitern. Die App bietet zwei verschiedene Lernmodi. Beim ersten Modus
lernt man mit "Karteikarten", die Vokabeln und ihre Übersetzungen enthalten. Der zweite Modus besteht aus
einem Multiple-Choice-Test, bei dem man die richtige Übersetzung auswählen muss. Nutzer können ihre eigenen
Vokabeln eingeben und speichern. Außerdem werden die Lernfortschritte gespeichert und können als Statistik
angezeigt werden.

=== Projektziele
* Entwicklung einer benutzerfreundlichen App für Schüler
* Implementierung von verschiedenen Lernmodi
* Implementierung einer Statistik um Lernfortschritte sichtbar zu machen
* Verminderung des Zeitaufwands um Vokabeln zu lernen
* Verminderung des Aufwands um Vokabeln zu verwalten (z.B. basteln von Karteikarten, ...)

=== Projektnutzen
Die Vokabel Lernapp erleichtert das Lernen von Vokabeln und hilft Nutzern ihre Sprachkenntnisse zu verbessern.
Durch die Interaktivität und die spielerische Wirkung der App wird die Motivation der Nutzer gesteigert.
Schüler müssen nicht mehr Zeit mit dem Erstellen von Karteikarten verschwenden und können sich auf das Lernen
konzentrieren. Außerdem können sie sich mithilfe der Multiple-Choice-Tests selbst abprüfen.

=== Konsequenzen bei Nichtdurchführung des Projekts
Ohne die Vokabel Lernapp sind Schüler auf weniger effektive Lernmethoden angewiesen. Das würde zu
geringeren Lernerfolgen führen und die Lernzeit steigern. Schüler müssten mehr Zeit aufwenden, um Vokabeln zu
lernen und Materialien zu erstellen, wodurch sie sich weniger motiviert fühlen würden.